/**
 * Downloads the web fonts from Google Fonts into public/fonts and writes
 * src/styles/fonts.css pointing at the local copies.
 *
 * We self-host rather than linking fonts.googleapis.com so the site has no
 * third-party runtime dependency, no extra DNS/TLS round trip before first
 * paint, and no requests leaking visitors' IPs to another origin.
 *
 * Re-run with:  node scripts/fetch-fonts.mjs
 */
import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  'Silkscreen:wght@400;700',
  'Nunito:ital,wght@0,400;0,600;0,700;0,800;1,400',
  'DM+Mono:wght@400;500',
];

/** Only the subsets we actually need; skips Cyrillic/Vietnamese bulk. */
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const outDir = resolve('public/fonts');
await mkdir(outDir, { recursive: true });

const query = FAMILIES.map((family) => `family=${family}`).join('&');
const response = await fetch(`https://fonts.googleapis.com/css2?${query}&display=swap`, {
  headers: { 'User-Agent': UA },
});
if (!response.ok) throw new Error(`Google Fonts returned ${response.status}`);
const css = await response.text();

// The CSS is a sequence of "/* subset */ @font-face { ... }" blocks.
const blocks = css.split(/(?=\/\*\s*[a-z-]+\s*\*\/)/i).filter((block) => block.includes('@font-face'));

const out = [
  '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */',
  '/* Self-hosted so the site has no third-party font dependency. */',
  '',
];
/** Google serves one variable file for every weight of a family; store it once. */
const byHash = new Map();
let downloaded = 0;

for (const block of blocks) {
  const subset = block.match(/\/\*\s*([a-z-]+)\s*\*\//i)?.[1];
  if (!subset || !KEEP_SUBSETS.has(subset)) continue;

  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*([^;]+);/)?.[1]?.trim();
  const style = block.match(/font-style:\s*([^;]+);/)?.[1]?.trim() ?? 'normal';
  if (!url || !family) continue;

  const fontResponse = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!fontResponse.ok) throw new Error(`${url} returned ${fontResponse.status}`);
  const bytes = Buffer.from(await fontResponse.arrayBuffer());
  const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 8);

  let file = byHash.get(hash);
  if (!file) {
    const slug = family.toLowerCase().replace(/\s+/g, '-');
    file = `${slug}-${subset}-${hash}.woff2`;
    await writeFile(resolve(outDir, file), bytes);
    byHash.set(hash, file);
    downloaded += 1;
  }

  out.push(
    block
      .replace(/\/\*[\s\S]*?\*\/\s*/, '')
      .replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('/fonts/${file}')`)
      .trim(),
    '',
  );
}

await writeFile(resolve('src/styles/fonts.css'), out.join('\n'));
console.log(`Downloaded ${downloaded} font files into public/fonts`);
